version: '0.1'
services:

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80" 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  db:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: my_db
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
